### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by AnnabellKuldmaa** [AnnabellKuldmaa/ds16#1]

**Comment by AnnabellKuldmaa** [comment]
1) Need get/set nupud võiksid olla mõistlikumas - 'Get permissions' ja 'Set permissions'
2) Connect nupp peab olema disabled, kui username ja ip pole mõlemad täidetud
3) Me peaksime kuvama avatud faili nime eraldi

**Comment by heikkisaul** [comment]
1) Nupud ja paigutus korrastatud
2) Connect nupp toimib ainult siis, kui aadressi ja kasutajanime lahtris midagi on. Hetkel pole aadressilahtris validaatorit, mis kontrolliks sisendi formaati. 
3) Kuvab avatud faili nime statusbaril (akna all vasakus nurgas). Uurin veel, kuidas saaks nupuvajutuse peale akna pealkirja muuta.

**Comment by heikkisaul** [comment]
.TODO 19.11 23:30 seisuga
1) New file nupp ei tohiks tekstiakent aktiveerida (see õigus ainult edit nupul. ma ei leidnud seda kohta praegu koodist üles).
2)Kui kasutajal kaob ära õigus mingit faili muuta, siis peaks tal tekstiaken deaktiveeruma ja tühjaks minema (ilma et fail tühjaks muutuks) kuni ta uue faili avab.
